name: "cargo"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Build
        run: cargo build -v -F regenerate
      - name: Upload generated.rs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target/debug
      - name: Run tests
        run: cargo test -v -F regenerate
